apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ghfx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fdna-tenant/rhtap-demo-app/hacbs-test-project-ghfx@sha256:defc6ad7552ff970e5b983d82a59ffe90284c5c2a7bedea16e319afb1aa32627
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
