apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ghfx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ghfx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ghfx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ghfx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ghfx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fdna-tenant/rhtap-demo-app/hacbs-test-project-ghfx@sha256:31f9dbbdf2031b1c6a79680d0a4b748ab454ef4ef076cfe5ea2ae6d0d6116d7e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
